# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "standard/rake"

require "rake/extensiontask"

task build: :compile

Rake::ExtensionTask.new("mqtt") do |ext|
  ext.lib_dir = "lib/mqtt"
end

task default: %i[clobber compile spec standard]
